version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: test-php
    volumes:
      - "./:/var/www/html/"
  web:
    container_name: test-web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8888:80"
      - "8887:81"
    volumes:
      - "./:/var/www/html/"
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: test-db
    ports:
      - "3307:3306" # mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
